# Ankit's DB
# development:
#   adapter: postgres
#   host: localhost
#   database: ankit
#   user:
#   password:

development:
  adapter: postgres
  host: localhost
  database: <your_database_name>
  user: <your_username (if present)>
  password: <your_password (if present)>

test:
  adapter: postgres
  host: localhost
  database: ankit_test
  user:
  password:

#postgres://bickfarfuwrdrd:551e4ca2dce8792eb5f47d59c7dbac7a89774bfb65716705e864dda0660cec0b@ec2-184-73-174-10.compute-1.amazonaws.com:5432/ddir985a9055e3
production:
  adapter: postgres
  host: ec2-184-73-174-10.compute-1.amazonaws.com
  database: ddir985a9055e3
  user: bickfarfuwrdrd
  password: 551e4ca2dce8792eb5f47d59c7dbac7a89774bfb65716705e864dda0660cec0b
